server:
  port: 8090
spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: sru_lib_management
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
      schema-locations: classpath:sql/schema.sql
      platform: mysql
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
hunter:
  api:
    key: ${HUNTER_API_KEY}
jwt:
  token: ${JWT_TOKEN}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    #org.springframework: DEBUG

